name: render index

# Controls when the action will run
on:
  push:
    branches: main
  schedule:
    - cron: "30 10 * * *"

jobs:
  render:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1

    # install packages needed
    - name: install required packages
      run: Rscript -e 'install.packages(c("rmarkdown","gratia","tidyverse", "zoo", "DT", "lubridate", "plotly"))'

    # Render READEME.md using rmarkdown
    - name: render README
      run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "html_document")'

    - name: commit rendered README
      run: |
        git add -A
        git commit -m "Re-build index.html" || echo "No changes to commit"
        git push origin main || echo "No changes to commit"